from __future__ import annotations

from typing import Protocol

from app.domain.models import AudioChunk, BeatEvent, LightingPrediction


class BeatTrackerAdapter(Protocol):
    def load(self) -> None: ...
    def reset(self) -> None: ...
    def ingest(self, chunk: AudioChunk) -> None: ...
    def get_events(self) -> list[BeatEvent]: ...


class SkipBartAdapter(Protocol):
    def load(self) -> None: ...
    def warmup(self) -> None: ...
    def reset(self) -> None: ...
    def predict(self, context: object) -> LightingPrediction | None: ...


class PreprocessorAdapter(Protocol):
    def transform(self, chunk: AudioChunk) -> object: ...


class PostprocessorAdapter(Protocol):
    def shape(self, prediction: LightingPrediction) -> LightingPrediction: ...
