from __future__ import annotations

from typing import Protocol

from app.domain.models import AudioChunk, BeatEvent, LightingPrediction


class BeatTrackerAdapter(Protocol):
    def load(self) -> None: ...
    def reset(self) -> None: ...
    def ingest(self, chunk: AudioChunk) -> None: ...
    def get_events(self) -> list[BeatEvent]: ...


class SkipBartAdapter(Protocol):
    """Streaming-style adapter contract.

    Skip-BART is non-causal in its original form (autoregressive over a full
    sequence), so the real adapter implements streaming as a sliding-window
    approximation. The contract here mirrors BeatTrackerAdapter so the pipeline
    can drain predictions the same way it drains beats.
    """

    def load(self) -> None: ...
    def warmup(self) -> None: ...
    def reset(self) -> None: ...
    def ingest(self, chunk: AudioChunk) -> None: ...
    def get_predictions(self) -> list[LightingPrediction]: ...


class PreprocessorAdapter(Protocol):
    def transform(self, chunk: AudioChunk) -> object: ...


class PostprocessorAdapter(Protocol):
    def shape(self, prediction: LightingPrediction) -> LightingPrediction: ...
