import simpleClub from './simple-club.json';
import edmFestival from './edm-festival.json';

export type StagePreset = {
  id: string;
  label: string;
  /** Raw imported JSON; validated through parseSceneDocument before use. */
  doc: unknown;
};

/** Bundled, importable stage presets (generated by scripts/generate-stages.ts). */
export const STAGE_PRESETS: StagePreset[] = [
  { id: 'simple-club', label: 'Club Night (simple)', doc: simpleClub },
  { id: 'edm-festival', label: 'EDM Festival (complex)', doc: edmFestival },
];
